### ISSUE TITLE
【Bug】看教程的title存在大量错误

### ISSUE THREAD

**Issue by jing8956** [overmind1980/oeasyorg#7]
看教程存在以下两种格式两种格式：
1. oeasy教你玩转XXX教程视频下教程
2. oeasy教你玩转XXX

因为存在两种格式不能确定，所以做了一半的提交出现两难只能放弃撤回
（闲话1：最后出现的“下教程”三个字好像是忘了删除被大量复制的。。。猜测本来应该想是“oeasy教你玩转XXX教程视频”
（闲话2：HTML的三个视频加起来都快50万的播放量了，结果从去年八月到现在算上我只有四个人来关心老师网站的建设。。。
（闲话3：还有一个点了Like和Fork之后啥也没干的。。。

**Comment by overmind1980** [comment]
是啊 这个我也不知道哪些内容可以参与进来 我就实时更新过来 
我看到您的留言也很激动 
终于有人和我在这里说句话了
您说的是这个两种格式是指的那个文件，什么位置呢？

**Comment by jing8956** [comment]
@overmind1980 

指的是各个教程页面的“看教程”a标签的title属性

### 具体位置
- 电路 (oeasy教你玩转XXX教程视频下教程)
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/circuit/circuit.html#L16
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/circuit/circuit.html#L23
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/circuit/circuit.html#L30
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/circuit/circuit.html#L37
- 系统 （两种混合）
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/system/system.html#L15
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/system/system.html#L21
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/system/system.html#L28
- 编程 （两种混合）
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/program/program.html#L16
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/program/program.html#L23
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/program/program.html#L30
- 前端 （两种混合，css和javascript存在错误）
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/web/web.html#L16
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/web/web.html#L24
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/web/web.html#L31
- 平面设计 （oeasy教你玩转XXX教程视频下教程，字体，icon，色彩构成错误）
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/graphic/graphic.html#L16
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/graphic/graphic.html#L25
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/graphic/graphic.html#L33
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/graphic/graphic.html#L40
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/graphic/graphic.html#L48
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/graphic/graphic.html#L55
- 影视后期 （oeasy教你玩转XXX教程视频下教程）
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/video/video.html#L16
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/video/video.html#L26
- 动画制作 （两种混合，全部错误）
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/animation/animation.html#L16
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/animation/animation.html#L25
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/animation/animation.html#L33
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/animation/animation.html#L40
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/animation/animation.html#L48
- 音频制作 （两种混合，全部错误）
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/audio/audio.html#L16
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/audio/audio.html#L25
    - https://github.com/overmind1980/oeasyorg/blob/0bb885f9c68e1e6fb7190c012e168fea7945ce90/category/audio/audio.html#L32
- 游戏 （两种混合，全部错误，同音频制作，位置略）
- 办公 （两种混合，全部错误，同音频制作，位置略）
- 日常 （两种混合，全部错误，同音频制作，位置略）

### 分析

- 大部分链接使用“oeasy教你玩转XXX教程视频下教程”
- 最后四个板块都只有三个教程，并且都是“oeasy教你玩转html5”、“oeasy教你玩转windows教程视频下教程”、“oeasy教你玩转ios教程视频下教程”
- 前面很多虽内容对应但格式混合的板块，也只有第一个教程不带“教程视频下教程”，推测所有不带“教程视频下教程”后缀是先做了上面三个链接之后直接复制手动修改漏掉了html5的导致。
- 但因为语境分析，后缀“下教程”与链接本身是B站链接“看教程”存在冲突，title最后的“下教程”三个字可能本身就是一个更前一次的复制错误，所以title修复无法进行，故提出这个Issues

**Comment by jing8956** [comment]
@overmind1980 感觉搞开源项目一般都是主持人或者主持团队搞具体内容在做项目的大部分工作，其他人一般都是在最终用产品的时候遇到问题才会参与进来。能具体推断出该怎么做、有能力、有时间的就改好提交Pull requests，没能力或者有争议的（闲人又不能做主）那就提Issues。也就这么些内容了

**Comment by overmind1980** [comment]
收到！感谢您认真的发现！我这个确实是复制粘贴，后来就懒了，没有管title的设置了。
马上就开学了，好多东西弄不过来了。感谢您的帮助和提醒！
我最近在实验楼做了一些东西，/oeasyorg/category/system/vim/这里，不过就像您说的，这东西还是得我主要来搞。
再次感谢您的帮助！！！

**Comment by jing8956** [comment]
@overmind1980 弄不过来的您可以说一下应该怎么弄，这样有空的人看到也可以来帮你做好提交Pull request。
老师在开vim新坑啊，~~虽然没有学这个的打算但还是~~祝老师开心幸福。

**Comment by overmind1980** [comment]
好的 好的 谢谢啦
